<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testsuite failures="1" name="cucumber.runtime.formatter.JUnitFormatter" skipped="0" tests="1" time="158.342315">
    <testcase classname="Defect Test" name="Payment" time="158.342315">
        <failure message="java.lang.AssertionError: expected:&lt;false&gt; but was:&lt;true&gt;&#13;&#10;&#9;at org.junit.Assert.fail(Assert.java:89)&#13;&#10;&#9;at org.junit.Assert.failNotEquals(Assert.java:835)&#13;&#10;&#9;at org.junit.Assert.assertEquals(Assert.java:120)&#13;&#10;&#9;at org.junit.Assert.assertEquals(Assert.java:146)&#13;&#10;&#9;at stepDefinition.DefectSD.user_enters_the_card_data(DefectSD.java:85)&#13;&#10;&#9;at ✽.Then User enters the card data(src/test/resources/Feature/Defect.feature:9)&#13;&#10;"><![CDATA[Given User in the Home page.................................................passed
When User click on Cart button..............................................passed
And User click on Pay button................................................passed
Then Payment Page is be visible.............................................passed
When User click on cards....................................................passed
Then User enters the card data..............................................failed

StackTrace:
java.lang.AssertionError: expected:<false> but was:<true>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at stepDefinition.DefectSD.user_enters_the_card_data(DefectSD.java:85)
	at ✽.Then User enters the card data(src/test/resources/Feature/Defect.feature:9)
]]></failure>
    </testcase>
</testsuite>
